name: Sync
on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync-cmd]
  schedule:
    - cron: "0 0,8,16 * * *"
jobs:
  sync:
    strategy:
      fail-fast: false
      matrix:
        branch: [alpha, beta]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
          ref: ${{ matrix.branch }}
      - run: |
          git fetch --quiet && git merge --ff-only origin/main && git push || true
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_AUTHOR_NAME: "sentrei-bot"
          GIT_COMMITTER_NAME: "sentrei-bot"
          GIT_AUTHOR_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
          GIT_COMMITTER_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
